name: 每月3号项目经理提醒

on:
  schedule:
    - cron: '0 9,10,11 3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.YFB_PM_REMIND_BOT_KEY}}
      with:
        msgtype: text
        content: 请各项目经理及时审核日报，并提交上月的项目周报。


