name: 每周二项目经理提醒

#on: push
on:
  schedule:
    - cron: '0 1,2,3 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.YFB_PM_REMIND_BOT_KEY}}
      with:
        msgtype: text
        content: 每周一项目经理提醒：请各项目经理及时审核上周日报，并提交上周的项目周报。


