name: 项目签退提醒

#on: push
on:
  schedule:
    - cron: '30 11-13 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.PSBC_CHECKIN_REMIND_BOT_KEY}}
      with:
        msgtype: text
        content: 签退提醒：请遵从项目管理组要求，每天按时打卡。项目组4、5月份规定要加班，延长周一至周五的工作时间为 8:30～19:00，每周周六远程加班，4月20日开始执行，请 19:00 后打卡签退。

