name: 项目签退提醒

#on: push
on:
  schedule:
    - cron: '30 10-12 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.PSBC_CHECKIN_REMIND_BOT_KEY}}
      with:
        msgtype: text
        content: 签退提醒：请遵从项目管理组要求，每天按时打卡。在每天18点后，打卡签退，整日出勤时长需满9小时，出勤满4小时但不足9小时，视为出勤0.5天；出勤少于4小时，视为未出勤。

