name: 项目签退提醒

#on: push
on:
  schedule:
    - cron: '30 12-13 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.PSBC_CHECKIN_REMIND_BOT_KEY}}
      with:
        msgtype: text
        content: 签退提醒：请遵从项目管理组要求，每天按时打卡。项目组4、5月份规定要加班，延长周一至周五的工作时间（现场办公：8:30-19:00，远程办公：8:30～20:30），每周周六远程加班工作时间为8:30-20:30，4月20日开始执行，请 20:30 后打卡签退。

