name: Work Log Remind Action

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WeChat Work notification by text
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.YFB_WORKLOG_REMIND_BOT_KEY}}
      with:
        msgtype: text
        content: 请按时填写工作日报。

